# required variables:
#   IMAGE_NAME
#     The docker image name
#     Example: jamesits/vyos-builder
#   BUILD_SCRIPT_BRANCH
#     A branch of https://github.com/vyos/vyos-build
#     Available value: crux, current
#   BUILD_BY
#   BUILD_TYPE
#     image type, release or development
#   BUILD_VERSION

name: $(BUILD_TYPE)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  BUILD_BY: "github@public.swineson.me"
  BUILD_TYPE: "release"
  IMAGE_NAME: "jamesits/vyos-builder"

trigger:
  batch: false
  branches:
    include: [ "master" ]
  paths:
    include: [ "/vyos/*" ]
    exclude: [ "README.md" ]

jobs:
  - job: image
    displayName: "build image"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 120

    strategy:
      matrix:
        1.2-iso:
          BUILD_SCRIPT_BRANCH: 'crux'
          BUILD_VERSION: '1.2.5'
          IMAGE_FORMAT: 'iso'
        1.3-iso:
          BUILD_SCRIPT_BRANCH: 'equuleus'
          BUILD_VERSION: '1.3.0-dev'
          IMAGE_FORMAT: 'iso'

    steps:
    - bash: 'sudo -E ./vyos/build.sh ${IMAGE_FORMAT}'
      displayName: 'image build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: '$(IMAGE_FORMAT)'

