name: $(IMAGE_NAME)-$(Date:yyyyMMdd).$(Rev:.r)
variables:
  IMAGE_NAME: "jamesits/vyos-builder"

trigger:
  batch: false
  branches:
    include: [ "master" ]
  paths:
    include: [ "/vyos-builder/*" ]
    exclude: [ "README.md" ]

jobs:
  - job: docker
    displayName: "docker build"
    pool:
      vmImage: "ubuntu-16.04"
    workspace:
      clean: all
    timeoutInMinutes: 120

    strategy:
      matrix:
        crux:
          BUILD_SCRIPT_BRANCH: 'crux'
        current:
          BUILD_SCRIPT_BRANCH: 'current'

    steps:
    - task: Bash@3
      displayName: 'docker build'
      inputs:
        targetType: filePath
        filePath: '$(BUILD_SOURCESDIRECTORY)/vyos-builder/build.sh'

    - task: Docker@1
      displayName: login
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: Jamesits
        command: login

    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: Jamesits
        command: 'Push an image'
        imageName: '$(IMAGE_NAME):$(BUILD_SCRIPT_BRANCH)'
